/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Thu Jun 20 15:41:34 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


